# Generated by Django 2.0.5 on 2018-05-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20180517_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentID',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
